---
- hosts: all
  name: "Test configurator integration"
  vars:
    debug: true

  tasks: 
    - name: "Testing TCP accessibility on flyServerCore 1 port:7"
      cmd: tcp_connect 
      args: "{{flyServerCore1IP}} 7 {{tcpTimeoutInSeconds}}" 
      
    - name: "Testing TCP accessibility on flyServerCore 1 port:1199"
      cmd: tcp_connect
      args: "{{flyServerCore1IP}} 1199 {{tcpTimeoutInSeconds}}"

    - name: "Testing HTTP accessibility on flyServerCore 1 port:80" 
      cmd: http_get 
      args: http://{{flyServerCore1IP}}:80/ping false {{httpTimeoutInSeconds}}
      
    - name: "Testing HTTP accessibility on flyServerCore 1 port:8080"
      cmd: http_get 
      args: http://{{flyServerCore1IP}}:8080/ping false {{httpTimeoutInSeconds}}
      
      #####################################################################################
      
    - name: "Testing TCP accessibility on flyServerCore 2 port:7"
      cmd: tcp_connect 
      args: "{{flyServerCore2IP}} 7 {{tcpTimeoutInSeconds}}" 
      
    - name: "Testing TCP accessibility on flyServerCore 2 port:1199"
      cmd: tcp_connect
      args: "{{flyServerCore2IP}} 1199 {{tcpTimeoutInSeconds}}"

    - name: "Testing HTTP accessibility on flyServerCore 2 port:80" 
      cmd: http_get 
      args: http://{{flyServerCore2IP}}:80/ping false {{httpTimeoutInSeconds}}
      
    - name: "Testing HTTP accessibility on flyServerCore 2 port:8080"
      cmd: http_get 
      args: http://{{flyServerCore2IP}}:8080/ping false {{httpTimeoutInSeconds}}
      
      ####################################################################################
      
    - name: "Testing Server time synchronisation with flyserver Core 2"
      cmd: time_sync 
      args: http://{{flyServerCore2IP}}:80/time {{httpTimeoutInSeconds}} {{tolerateSyncDiffInMillis}}
      
      ####################################################################################
      
    - name: "Check if intravision group exist and not empty"
      cmd: ldap_is_group_empty
      args: '"{{activeDirectoryHostname}}" "{{activeDirectoryPort}}" "{{activeDirectoryUserName}}" "{{activeDirectoryPassword}}" "{{activeDirectoryIntravisionGroup}}" "{{activeDirectoryUsersRootDN}}"'

    - name: "Check ldap translator groups exist and not empty"
      cmd: ldap_translator
      args: '"{{activeDirectoryHostname}}" "{{activeDirectoryPort}}" "{{activeDirectoryUserName}}" "{{activeDirectoryPassword}}" "{{activeDirectoryUsersRootDN}}"'
      when : ldapTranslatorExist
