---
- hosts: all
  name: "Test flyserverCore intern"
  vars:
    debug: true

  tasks: 
 
    - name: "Check if Windows server version is between 2008 and 2022"
      cmd: windows_validity
      args: 2008 2022
      
      
    - name: "Intern 200 Points"
      cmd: include_tasks
      args: "{{playbookFolder}}\\flyserverCore200points.yaml"
      when : measurementPoints === 200
      
    - name: "Intern 1000 Points"
      cmd: include_tasks
      args: "{{playbookFolder}}\\flyserverCore1000points.yaml"
      when : measurementPoints === 1000
####################################################################################  
    - name: "Testing HTTP availability on local port:80"
      cmd: http_availability
      args: 80
      
    - name: "Testing HTTP accessibility on local port:80"
      cmd: http_get 
      args: http://localhost:80/ping false {{httpTimeoutInSeconds}}
       
####################################################################################  
    - name: "Testing HTTP availability on local port:4646"
      cmd: http_availability
      args: 4646
      
    - name: "Testing HTTP accessibility on local port:4646"
      cmd: http_get 
      args: http://localhost:4646/ping false {{httpTimeoutInSeconds}}

####################################################################################
    - name: "Testing HTTP availability on local port:8079"
      cmd: http_availability
      args: 8079
      
    - name: "Testing HTTP accessibility on local port:8079"
      cmd: http_get 
      args: http://localhost:8079/ping false {{httpTimeoutInSeconds}}
      
####################################################################################
    - name: "Testing HTTP availability on local port:8077"
      cmd: http_availability
      args: 8077
      
    - name: "Testing HTTP accessibility on local port:8077"
      cmd: http_get 
      args:  http://localhost:8077/ping false {{httpTimeoutInSeconds}}
      
####################################################################################
    - name: "Testing HTTP availability on local port:8080"
      cmd: http_availability
      args: 8080
      
    - name: "Testing HTTP accessibility on local port:8080"
      cmd: http_get 
      args: http://localhost:8080/ping false {{httpTimeoutInSeconds}}
      
####################################################################################
    - name: "Testing HTTP availability on local port:8083"
      cmd: http_availability
      args: 8083
      
    - name: "Testing HTTP accessibility on local port:8083"
      cmd: http_get 
      args: http://localhost:8083/ping false {{httpTimeoutInSeconds}}

####################################################################################       

    - name: "Testing TCP availability on local port:1199"
      cmd: tcp_availability
      args: 1199
      
####################################################################################

    - name: "Testing TCP availability on local port:7"
      cmd: tcp_availability
      args: 7
      
####################################################################################

    - name: "Testing HTTPS availability on local port:443"
      cmd: https_availability
      args: 443
      
    - name: "Testing HTTPS accessibility on local port:443"
      cmd: http_get 
      args: https://localhost:443/ping true {{httpTimeoutInSeconds}}